version: "3.5"
services:
  url_pg:
    image: "postgres:latest"
    ports:
      - "13080:5432"
    networks:
      - mynetwork
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  server:
    build: ./
    restart: always
    # container_name: server
    depends_on:
      - url_pg
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - mynetwork

networks:
  mynetwork:
