// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/kuzkuss/url_service/models"
	mock "github.com/stretchr/testify/mock"
)

// UseCaseI is an autogenerated mock type for the UseCaseI type
type UseCaseI struct {
	mock.Mock
}

// CreateShortLink provides a mock function with given fields: link
func (_m *UseCaseI) CreateShortLink(link *models.Link) error {
	ret := _m.Called(link)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Link) error); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOriginalLink provides a mock function with given fields: link
func (_m *UseCaseI) GetOriginalLink(link string) (string, error) {
	ret := _m.Called(link)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCaseI interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCaseI creates a new instance of UseCaseI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCaseI(t mockConstructorTestingTNewUseCaseI) *UseCaseI {
	mock := &UseCaseI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
