// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: link.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinksClient is the client API for Links service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinksClient interface {
	CreateShortLink(ctx context.Context, in *OriginalLink, opts ...grpc.CallOption) (*ShortLink, error)
	GetOriginalLink(ctx context.Context, in *ShortLink, opts ...grpc.CallOption) (*OriginalLink, error)
}

type linksClient struct {
	cc grpc.ClientConnInterface
}

func NewLinksClient(cc grpc.ClientConnInterface) LinksClient {
	return &linksClient{cc}
}

func (c *linksClient) CreateShortLink(ctx context.Context, in *OriginalLink, opts ...grpc.CallOption) (*ShortLink, error) {
	out := new(ShortLink)
	err := c.cc.Invoke(ctx, "/link.Links/CreateShortLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) GetOriginalLink(ctx context.Context, in *ShortLink, opts ...grpc.CallOption) (*OriginalLink, error) {
	out := new(OriginalLink)
	err := c.cc.Invoke(ctx, "/link.Links/GetOriginalLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinksServer is the server API for Links service.
// All implementations must embed UnimplementedLinksServer
// for forward compatibility
type LinksServer interface {
	CreateShortLink(context.Context, *OriginalLink) (*ShortLink, error)
	GetOriginalLink(context.Context, *ShortLink) (*OriginalLink, error)
	mustEmbedUnimplementedLinksServer()
}

// UnimplementedLinksServer must be embedded to have forward compatible implementations.
type UnimplementedLinksServer struct {
}

func (UnimplementedLinksServer) CreateShortLink(context.Context, *OriginalLink) (*ShortLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShortLink not implemented")
}
func (UnimplementedLinksServer) GetOriginalLink(context.Context, *ShortLink) (*OriginalLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOriginalLink not implemented")
}
func (UnimplementedLinksServer) mustEmbedUnimplementedLinksServer() {}

// UnsafeLinksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinksServer will
// result in compilation errors.
type UnsafeLinksServer interface {
	mustEmbedUnimplementedLinksServer()
}

func RegisterLinksServer(s grpc.ServiceRegistrar, srv LinksServer) {
	s.RegisterService(&Links_ServiceDesc, srv)
}

func _Links_CreateShortLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginalLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).CreateShortLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/link.Links/CreateShortLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).CreateShortLink(ctx, req.(*OriginalLink))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_GetOriginalLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).GetOriginalLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/link.Links/GetOriginalLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).GetOriginalLink(ctx, req.(*ShortLink))
	}
	return interceptor(ctx, in, info, handler)
}

// Links_ServiceDesc is the grpc.ServiceDesc for Links service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Links_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "link.Links",
	HandlerType: (*LinksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShortLink",
			Handler:    _Links_CreateShortLink_Handler,
		},
		{
			MethodName: "GetOriginalLink",
			Handler:    _Links_GetOriginalLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "link.proto",
}
